name: test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0

    - uses: olafurpg/setup-scala@v13
      with:
        java-version: openjdk@21.0.2=tgz+https://download.java.net/java/GA/jdk21.0.2/f2283984656d49d69e91c558476027ac/13/GPL/openjdk-21.0.2_linux-x64_bin.tar.gz

    - name: Test
      run: |
        sbt 'scalafmtCheckAll' 'zikyo-core/test' 'zikyo-coreJS/test'